name: Build ESP-AT Project

on: push

jobs:
  build-esp32c2-4mb-ble-spi-at:
    uses: ./.github/workflows/build_template_esp32c2.yml
    with:
      module_name: ESP32C2-4MB-BLE-SPI
      artifacts_name: esp32c2-4MB-ble-spi-at
      enable_ble_cmds: true
    secrets: inherit

  build-esp32c2-2mb-ble-spi-at:
    uses: ./.github/workflows/build_template_esp32c2.yml
    with:
      module_name: ESP32C2-2MB-BLE-SPI
      artifacts_name: esp32c2-2mb-ble-spi-at
    secrets: inherit
